@startuml
'------------------------- Fonts & Defs
'skinparam backgroundColor LightYellow
skinparam defaultFontName Monaco
skinparam package {
 	BackgroundColor LightGrey
}
center footer CC BY-SA 4.0 - http://jmbruel.github.io - 2016
hide members
show methods
'------------------------- Main components
package android #DDDDDD {
	package android.view {
		class "View" as v << (A,green)>> {
			setId(int)
		}
		class "ViewGroup" as vg << (A,green)>>
		v <|-- vg
	}
	package android.widget {
		class "TextView" as tv << (A,green)>> {
			setText(...)
		}	
		class "Button" as b << (A,green)>>
		class "Spinner" as spinner << (A,green)>>
		v <|-- spinner
		class EditText << (A,green)>>
		tv <|-- EditText
		class RelativeLayout << (A,green)>>
		class LinearLayout << (A,green)>>
		class GridLayout << (A,green)>>
		vg <|-- RelativeLayout
		vg <|-- LinearLayout
		vg <|-- GridLayout
		
	}
	package android.app #DDDDDD {
		abstract class Activity << (A,green)>> {
			onCreate(Bundle)
		}
		abstract class CRUDActivity << (A,green)>>
		class DashboardActivity << (A,green)>>
		Activity <|-- CRUDActivity
		Activity <|-- DashboardActivity
		package fragment {
			abstract class Fragment << (A,green)>>
	  	}
		Class Context << (A,green)>> {
			startActivity()
		}
		Class ContextWrapper  << (A,green)>>
		Class ContextThemeWrapper  << (A,green)>>
		Context <|-- ContextWrapper
		ContextWrapper <|-- ContextThemeWrapper
		ContextThemeWrapper <|-- Activity
	}
}
package layout #DDDDDD {
	class Layout << (A,green)>>
	Layout *-- v
}
package Resources #DDDDDD {
  class "String.xml" as String << (X,green)>>
}
package com.MyCompany #FFFFF {
	Application *--> MyActivity
}
v <|-- tv
tv <|-- b
class Layout << (X,white) >>
'----------------------------
Activity --> Activity
Activity <|-- MyActivity
MyActivity -> Layout
String  <.. Layout
@enduml